### ISSUE TITLE
Firefox browser extension/add-on

### ISSUE THREAD

**Issue by rugk** [padlock/padlock#216] opened 2019-06-26 10:41 UTC
You already have a Chrome/ium extension.

But you really should support Firefox, too! As both use the same technology stack (WebExtensions/browser extensions), it [should be quite easy to port](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension) your extension to Firefox, as [there are not that many differences](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities) (and Firefox actually often has a lot more/better APIs).

So please do so, only supporting one browser is no option and [hurts browser diversity](https://css-tricks.com/the-ecological-impact-of-browser-diversity/).

**Comment by jimvonmoon** [comment] 2019-06-26 11:03
Is the Chromium extension really available? I don't think it is. This issue might be a bit ahead of itself as I don't think Padlock even has a Native Messaging API for interacting with browser extensions in general.

**Comment by rugk** [comment] 2019-06-26 11:06
I only checked there website. There was an link and so on… :thinking:

**Comment by rugk** [comment] 2019-06-26 11:08
Oh wtf [the link on this page](https://padlock.io/downloads/) is a 404 one. But considering one cannot _imagine_ that crazy URL the Chrome extension store creates there, I guess they might have something planned/uploaded already (but private or so?).

**Comment by jimvonmoon** [comment] 2019-06-26 11:18
Yeah, the link seems to be dead now, and I am not sure if it led to the kind of extension you would expect in the first place (i.e. integration with browser's password manager). Though I agree this should be a priority. Especially in case of Firefox, which is notorious for its default password manager's flawed security.

**Comment by rugk** [comment] 2019-06-26 11:27
Off-topic, but Firefox is absolutely working on it's password manager right now (making it as Firefox Lockwise). Anyway, that's off-topic.

**Comment by MaKleSoft** [comment] 2019-06-26 16:04
The Chrome link isn't an extension but a standalone Chrome App. Google canceled support for standalone Chrome apps for platforms other than ChromeOS a while ago which is probably why the link is broken now. We're planning to ship actual browser extensions for all major browsers shortly after the v3 release. Closing this as duplicate of https://github.com/padlock/padlock/issues/82

**Closed by MaKleSoft** 2019-06-26 16:04 UTC

**Comment by rugk** [comment] 2019-06-27 12:38
Okay, then. But then I'd suggest to remove that link. :smile:
