### ISSUE TITLE
Unlock app with touch id

### ISSUE THREAD

**Issue by alxmiron** [padlock/padlock#202] opened 2018-10-06 18:43 UTC
Padlock is a great project, but entering masterpassword takes too much time of my life! It would be nice if I could do it with touch id since many mobile devices and some laptops already have a fingerprint scanner

**Comment by MaKleSoft** [comment] 2018-10-08 08:02
Duplicate of https://github.com/padlock/padlock/issues/21

**Closed by MaKleSoft** 2018-10-08 08:02 UTC
